# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nick Paolini
# Description of the Site
description: ANALYST AND DEVELOPER
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.discordapp.com/attachments/437820509741121536/856228315735916554/20210620_134525.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: npaolini@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: nick-paolini
github_username:  npaolini-8
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Nick Paolini
# URL for the Image of the Author
author-image: https://cdn.discordapp.com/attachments/683692219345010761/928147612467605524/unknown.png
# 60 Words About the Author
author-about: Analytical thinker who enjoys seeking out opportunities to solve problems and design valuable solutions. See blog for software projects!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/npaolini-8

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
